### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LeftistTachyon** [LeftistTachyon/BattleTetris#1]
Exception in thread "Thread-4" java.lang.NullPointerException
	at simpletetris.TetrisMatrix.moveTetToStart(TetrisMatrix.java:826)
	at simpletetris.TetrisMatrix.newPiece(TetrisMatrix.java:814)
	at simpletetris.TetrisMatrix.start(TetrisMatrix.java:334)
	at simpletetris.TetrisPanel.lambda$startGame$4(TetrisPanel.java:211)
	at java.lang.Thread.run(Thread.java:748)

'Cause you're trying to move `null` to the start. The bag is empty.

**Comment by LeftistTachyon** [comment]
Fixed, but not really?

**Comment by LeftistTachyon** [comment]
Really. The exception is different
