### ISSUE TITLE
Bags not synchronized: causing ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by LeftistTachyon** [LeftistTachyon/BattleTetris#3]
`Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 10`
`    at simpletetris.TetrisMatrix.lockPiece(TetrisMatrix.java:900)`
`    at simpletetris.TetrisMatrix.lockFalling(TetrisMatrix.java:1488)`

**Comment by LeftistTachyon** [comment]
Done
